apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-to-frontend
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: reliability-frontend
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
          podSelector:
            matchLabels:
              gateway.envoyproxy.io/owning-gateway-name: reliability-gateway
              gateway.envoyproxy.io/owning-gateway-namespace: reliability
      ports:
        - protocol: TCP
          port: 8080
