apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: reliability-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: k8slab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reliability-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
