apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reliability

resources:
  - ../../base
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml

images:
  - name: ghcr.io/myomyatmin/k8slab-api
    digest: sha256:80b24677fbb67cbaacb2334d584a7f98cbc8e9b6f8dab25cb582869ae13a77e5
  - name: ghcr.io/myomyatmin/k8slab-frontend
    digest: sha256:e0f89ae8c39963d2c10b3821152da43b7503b9f767e63b2d28b355937593178f

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          reliability.dev/workload: "true"
