apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reliability

resources:
  - ../../base
  - ../../policies
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - envoy-proxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - http-route.yaml

images:
  - name: ghcr.io/myomyatmin/k8slab-api
    digest: sha256:89c3cfefddbca7bb6ae513418d6f830ae55941e7d036a6e438fa2216bb268863
  - name: ghcr.io/myomyatmin/k8slab-frontend
    digest: sha256:d2643e31dec5e1f781a23aab7ae63ad33cdceef9b346693ccf587eeef90ee161

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          reliability.dev/workload: "true"
