apiVersion: v1
kind: ResourceQuota
metadata:
  name: reliability-quota
  namespace: reliability
  labels:
    app.kubernetes.io/name: reliability-quota
    app.kubernetes.io/part-of: k8slab
    app.kubernetes.io/component: resource-boundary
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
